### ISSUE TITLE
Support for the `/ping` health check endpoint

### ISSUE THREAD

**Issue by PiDelport** [onfido/onfido-openapi-spec#19]
Can the <https://documentation.onfido.com/#ping> endpoint be added to the OpenAPI spec?

**Comment by Phoebe-B** [comment]
Hi @PiDelport Thanks for getting in touch. Yes we can add the Ping endpoint. I will try and look into this soon and will let you know when we have implemented this addition.

**Comment by PiDelport** [comment]
Thanks! 🙂

**Comment by Phoebe-B** [comment]
The Ping endpoint has now been added in v2.2.0-beta. Thanks again for getting in touch and hope this helps. 😃
