### ISSUE TITLE
Please add check_id as a property of the report.yaml schema file

### ISSUE THREAD

**Issue by Nialld** [onfido/onfido-openapi-spec#3]
At the moment, if you receive a webhook update regarding a report, there is no way of associating this to the parent check, debugging the code shows that the check_id does come back with the API request but as there is no check_id property so it cant be extracted from the. I would attempt a PR here myself but im not aware of the flow on effects of building the libraries for the various languages.

**Comment by ciaran16** [comment]
Thanks for opening an issue @Nialld! We've updated the spec and released an updated version of our PHP client as well https://github.com/onfido/api-php-client/releases/tag/5.0.1
