### ISSUE TITLE
Create Applicant Error does not match expected format.

### ISSUE THREAD

**Issue by drPytho** [onfido/onfido-openapi-spec#6]
`{"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"address":[{"postcode":["can't be blank"]}]}}} `

Does not match the generated code from https://openapi-generator.tech/ for the https://github.com/onfido/onfido-openapi-spec/blob/master/responses/default_error.yaml. 

The `additionalProperties: true` is not expected to be a list of objects (as returned by API) but rather an object on its own. https://swagger.io/docs/specification/data-models/dictionaries/. See free-form.

**Comment by ciaran16** [comment]
Hi @drPytho, `additionalProperties: true` applies to `"fields"` here, which is a free-form object in your example. The values of the `"fields"` object can still be if any type though, including lists/arrays.

**Comment by ciaran16** [comment]
Going to close this, but feel free to reopen if you think there's still an issue, or you can email api@onfido.com
